* POC: imapsieve with virtual mailboxes
dovecot/pigeonhole pull request #10
Opened 2021-11-20 12:54 UTC by allgood

[I've reported in the mailing list a few weeks ago](https://www.dovecot.org/list/dovecot/2021-October/123212.html) about the imapsieve plugin not working when moving messages into virtual folders that have a storage folder defined (the ! sign on the virtual configuration)

Not having any answer I've started to learn about how dovecot and pigeonhole executes this feature and figured out why it wasn't working and made this **Proof of Concept**.

It is only a **POC** because I am pretty sure that my code is not the best way to solve this, I am not an efficient C programmer and I never looked to any dovecot/pigeonhole code before this work.

Please take a look at this situation and convert it on a more acceptable change.

Best regards,
Claudemir

2021-11-22 23:30 UTC, sirainen requested changes
Also sent to mailing list:

Pigeonhole shouldn't need to know anything about this being a virtual mailbox specifically. If I understand right, the problem is that imapsieve doesn't like it when the destination folder doesn't know what the IMAP UID number is for the saved/copied mail. Earlier versions assert-crash, while a newer code just ignores this situation and doesn't execute the script. I think your patch works by returning the real folder's UID, not the virtual folder's UID. But imapsieve is still working on the virtual folder, so the UID likely points to a wrong message. 

Fixing this is rather difficult. It can't even be fixed in all situations. For example what happens if you have Virtual/Flagged folder that only has mails that have the \Flagged flag, and you copy a mail there without the flag? It gets saved to the real folder, but it won't show up in the Virtual/Flagged folder itself until later when it gets a \Flagged flag. What happens when you copy/save some mails that have the \Flagged flag and some that don't? Only some of the mails will end up in the virtual folder. Neither IMAP nor the current lib-storage API allows filling saved_uids only partially.

It could be a possibility to fix this for the specific situations when the saved mails are guaranteed to end up in the virtual folder. Detecting whether this is true could be a bit tricky in itself, although it could work for most cases by just supporting it when the virtual search query is "all". The next step would be to make the virtual transaction actually save the mails directly to the virtual indexes instead of going through the generic "virtual sync" code. Although I'm not sure how it would handle a situation when the real folder already had some new mails that weren't yet in the virtual index. The syncing might be smart enough to add those mails later, I'm not sure.

A completely different way of solving it might be to never actually save mails to a virtual folder directly. So e.g. when saving to Virtual/All the folder would be early on converted to INBOX, so imapsieve code would be thinking that the mail is being saved to INBOX. Maybe something like:
 - virtual_mailbox_alloc() checks if MAILBOX_FLAG_SAVEONLY is used. If yes, return the real mailbox instead of the virtual mailbox.
 - But this could cause much confusion for callers that don't expect it. So probably require also a new flag MAILBOX_FLAG_BACKEND_SAVEONLY.
 - Change the important places to support MAILBOX_FLAG_BACKEND_SAVEONLY properly. At least with IMAP when this is used and the mailbox isn't the expected mailbox, it shouldn't return [COPYUID] or [APPENDUID] response codes to COPY/APPEND commands since the returned UIDs would be for the real mailbox rather than the virtual mailbox.
 - It's also possible that this behavior would break some plugins..

2021-11-23 19:01 UTC, allgood commented
Hi @sirainen 

> I think your patch works by returning the real folder's UID, not the virtual folder's UID. But imapsieve is still working on the virtual folder, so the UID likely points to a wrong message.

the changes I made allows imapsieve to detect it is working with a virtual folder and then gets the UID and real folder of the message allowing to run the script. The script will see the real folder name and real uid, so, it will always point to the right message. This obviously only works if the virtual folder have a real folder fallback for saving.

> For example what happens if you have Virtual/Flagged folder that only has mails that have the \Flagged flag, and you copy a mail there without the flag?

I didn't tested, but the changes I made only targets the COPY/MOVE reason, I tested the FLAG reason and it was already sending the real folder location to the script, so I never tried to change this behaviour.

I didn't tested anything with the APPEND reason... maybe there is some work to do on this front.

I made clear that my implementation probably was not the best way to do it, mainly because I had to paste two `struct` definitions that I'm sure should have been included, and possibly make imapsieve and virtual plugins be related somehow.

My main concern is that imapsieve runs when a message is dropped on a virtual folder that have a save fallback real folder.

2021-11-23 22:12 UTC, allgood commented
Hi @sirainen 

a little update to my previous message.

tested with APPEND and FLAG

> what happens if you have Virtual/Flagged folder that only has mails that have the \Flagged flag, and you copy a mail there without the flag?

Note that APPEND and COPY/MOVE into a virtual mailbox that doesn't have a real mailbox fallback will never work, so, a virtual mailbox that only shows flagged messages cannot have a fallback folder, so, the answer for your question is: nothing... message will not be saved, and the imapsieve script will not run.

My patch fixed the behavior when APPEND and COPY reason are triggered on a virtual mailbox that have a real mailbox fallback for saving (configured through the ! operator on the virtual mailbox definition)

When FLAGGING a message stored on a virtual mailbox, imapsieve script is not running, this is because my patch isn't triggered on this situation.

Anyway I think it can be fixed the same way: execute the imapsieve passing the real message on the real mailbox... I may try to look at this, but I wasn't interested on FLAG action.

(I've made this tests with my patch applied on dovecot 2.3.13 on Debian Bullseye)

2021-11-25 12:36 UTC, allgood commented
One more update:

> When FLAGGING a message stored on a virtual mailbox, imapsieve script is not running, this is because my patch isn't triggered on this situation.
>
> Anyway I think it can be fixed the same way: execute the imapsieve passing the real message on the real mailbox... I may try to look at this, but I wasn't interested on FLAG action.
>
> (I've made this tests with my patch applied on dovecot 2.3.13 on Debian Bullseye)

Tested now with HEAD of master branch with my patches disabled... FLAG command is already being passed to imapsieve script with the virtual folder name on both environment information (vnd.dovecot.mailbox-to and vnd.dovecot.mailbox-from), with correct contents of the message flagged.

As my objective is hook antispam learning (with my changes enabling this when user take actions on virtual folders), this is sufficient. Maybe this can be changed to inform the real mailbox name of the message, but I think this is irrelevant.

2022-02-24 07:39 UTC, closed without merging

2022-02-24 11:51 UTC, allgood commented
@sirainen ... looks like the closure of this pull request was because of changing the branch name from  `master` to `main`.

The code I made is working good on my side but I need some help from who knows best the dovecot code to make it cleaner. My main concern is that I had to duplicate two `struct` definitions from project `dovecot/core`, that should be only included but was unable to do it. May be its needed a combination of changes on both projects to allow a better integration on this feature.

2022-02-24 12:11 UTC, sirainen commented
I don't think there's a way to change this current patch to be clean enough to get it merged. The Pigeonhole code really just shouldn't be trying to support virtual plugin specifically. It'll only lead to troubles/kludges sooner or later.

I think the idea in my first commit might work without too much kludging though. Can you see if it works? Something like this (untested, maybe crashes):

```
diff --git a/src/imap/imap-commands-util.c b/src/imap/imap-commands-util.c
index 6d8a292aed..2fc4c2d164 100644
--- a/src/imap/imap-commands-util.c
+++ b/src/imap/imap-commands-util.c
@@ -111,7 +111,8 @@ int client_open_save_dest_box(struct client_command_context *cmd,
 		*destbox_r = cmd->client->mailbox;
 		return 0;
 	}
-	box = mailbox_alloc(ns->list, name, MAILBOX_FLAG_SAVEONLY);
+	box = mailbox_alloc(ns->list, name, MAILBOX_FLAG_SAVEONLY |
+			    MAILBOX_FLAG_BACKEND_SAVEONLY);
 	if (mailbox_open(box) < 0) {
 		error_string = mailbox_get_last_error(box, &error);
 		if (error == MAIL_ERROR_NOTFOUND) {
diff --git a/src/lib-storage/mail-storage.h b/src/lib-storage/mail-storage.h
index 64e0e49a34..dd19035801 100644
--- a/src/lib-storage/mail-storage.h
+++ b/src/lib-storage/mail-storage.h
@@ -75,6 +75,7 @@ enum mailbox_flags {
 	   plugin to determine correctly whether the mailbox should be allowed
 	   to be opened. */
 	MAILBOX_FLAG_ATTRIBUTE_SESSION	= 0x10000,
+	MAILBOX_FLAG_BACKEND_SAVEONLY	= 0x20000,
 };
 
 enum mailbox_feature {
diff --git a/src/plugins/virtual/virtual-storage.c b/src/plugins/virtual/virtual-storage.c
index f88a279752..e589c360dc 100644
--- a/src/plugins/virtual/virtual-storage.c
+++ b/src/plugins/virtual/virtual-storage.c
@@ -39,6 +39,8 @@ struct virtual_storage_module virtual_storage_module =
 static MODULE_CONTEXT_DEFINE_INIT(virtual_backend_storage_module,
 				  &mail_storage_module_register);
 
+static void virtual_mailbox_free(struct mailbox *box);
+
 static bool ns_is_visible(struct mail_namespace *ns)
 {
 	return (ns->flags & NAMESPACE_FLAG_LIST_PREFIX) != 0 ||
@@ -274,6 +276,19 @@ virtual_mailbox_alloc(struct mail_storage *_storage, struct mailbox_list *list,
 	mbox->virtual_ext_id = (uint32_t)-1;
 	mbox->virtual_ext2_id = (uint32_t)-1;
 	mbox->virtual_guid_ext_id = (uint32_t)-1;
+
+	if ((flags & MAILBOX_FLAG_BACKEND_SAVEONLY) != 0) {
+		int ret = virtual_config_read(mbox);
+		if (ret == 0 || mbox->save_bbox != NULL) {
+			struct mail_namespace *ns =
+				mail_namespace_find(_storage->user->namespaces,
+						    mbox->save_bbox->name);
+			struct mailbox *box =
+				mailbox_alloc(ns->list, mbox->save_bbox->name, flags);
+			virtual_mailbox_free(&mbox->box);
+			return box;
+		}
+	}
 	return &mbox->box;
 }
 
```

2022-02-24 12:19 UTC, allgood commented
@sirainen I will check.

Is this supposed to make `dovecot/pigeonhole` run imapsieve scripts when moving to or from virtual boxes that have a backend storage with correct folder paths?

2022-02-24 12:29 UTC, sirainen commented
The idea is that if you've configured Virtual/foo to point to a RealFolder, then when doing COPY/MOVE/APPEND to Virtual/foo it early on changes the folder directly to RealFolder, so Pigeonhole code won't see the Virtual/foo at any point. This can also lead to troubles, but I think those troubles could be fixable.

My patch only change the COPY/MOVE destination. I think there's no problem using virtual folder as COPY/MOVE source?

2022-02-24 14:30 UTC, allgood commented
Didn't tested yet, but I think that APPEND should be supported also. On my case, messages saved on "Sent" should be learned as "ham", and if some client APPEND a message on Spam folder, it should trigger the learning of it as "spam".

The impact of the lack of support on APPEND is minimal, but I think we can't trust the client to issue the correct command, I think I've already saw Outlook using APPEND when it should use COPY/MOVE.

2022-02-25 15:19 UTC, allgood commented
Hi @sirainen 

made some tests:

Dovecot tests:

With "main" HEAD:

imapsieve script run when:
* APPEND to virtual folder - passing real folder name
* FLAG message on virtual folder - passing virtual folder name

imapsieve doesn't run (without server crash) when:
* COPY to virtual folder (MOVE not tested - Thunderbird always use COPY)


After applying patch on dovecot/core:

imapsieve script run when:
* APPEND to virtual folder - passing real folder name
* FLAG message on virtual folder - passing virtual folder name

Following crash is occuring when running some operations (opening INBOX, Moving messages, etc) on thunderbird client:

```
Feb 25 12:13:36 locutus dovecot: imap(allgood)<1468373><skSPJNnYQJR/AAAB>: Panic: file mail-storage.c: line 2927 (mailbox_get_path): assertion failed: (box->_path != NULL)
Feb 25 12:13:36 locutus dovecot: imap(allgood)<1468373><skSPJNnYQJR/AAAB>: Error: Raw backtrace: /opt/dovecot/lib/dovecot/libdovecot.so.0(backtrace_append+0x42) [0x7fed8cad90b2] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(backtrace_get+0x1e) [0x7fed8cad91ce] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(+0x103e0b) [0x7fed8cae5e0b] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(+0x103ea1) [0x7fed8cae5ea1] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(+0x56400) [0x7fed8ca38400] -> /opt/dovecot/lib/dovecot/libdovecot-storage.so.0(+0x403e8) [0x7fed8cbf53e8] -> /opt/dovecot/lib/dovecot/lib20_virtual_plugin.so(virtual_config_read+0x6d) [0x7fed8c9d4e2d] -> /opt/dovecot/lib/dovecot/lib20_virtual_plugin.so(+0xb468) [0x7fed8c9d7468] -> /opt/dovecot/lib/dovecot/libdovecot-storage.so.0(mailbox_alloc+0xbf) [0x7fed8cc1767f] -> dovecot/imap(client_open_save_dest_box+0x83) [0x55d42d741b83] -> dovecot/imap(+0x13a66) [0x55d42d732a66] -> dovecot/imap(command_exec+0xa4) [0x55d42d741434] -> dovecot/imap(+0x2035f) [0x55d42d73f35f] -> dovecot/imap(+0x2040a) [0x55d42d73f40a] -> dovecot/imap(+0x2071d) [0x55d42d73f71d] -> dovecot/imap(client_handle_input+0x1b5) [0x55d42d73f8e5] -> dovecot/imap(client_input+0x70) [0x55d42d73fe50] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(io_loop_call_io+0x69) [0x7fed8cafc0f9] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(io_loop_handler_run_internal+0x132) [0x7fed8cafd7e2] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(io_loop_handler_run+0x50) [0x7fed8cafc1a0] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(io_loop_run+0x40) [0x7fed8cafc360] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(master_service_run+0x13) [0x7fed8ca70853] -> dovecot/imap(main+0x50c) [0x55d42d730efc] -> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7fed8c81dd0a] -> dovecot/imap(_start+0x2a) [0x55d42d730fca]
Feb 25 12:13:36 locutus dovecot: imap(allgood)<1468373><skSPJNnYQJR/AAAB>: Fatal: master: service(imap): child 1468373 killed with signal 6 (core dumps disabled - https://dovecot.org/bugreport.html#coredumps)
Feb 25 12:13:36 locutus dovecot: imap-login: Login: user=<allgood>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=1468376, secured, session=<kJ+PJNnYQpR/AAAB>
Feb 25 12:13:36 locutus dovecot: imap(allgood)<1468376><kJ+PJNnYQpR/AAAB>: Panic: file mail-storage.c: line 2927 (mailbox_get_path): assertion failed: (box->_path != NULL)
Feb 25 12:13:36 locutus dovecot: imap(allgood)<1468376><kJ+PJNnYQpR/AAAB>: Error: Raw backtrace: /opt/dovecot/lib/dovecot/libdovecot.so.0(backtrace_append+0x42) [0x7fa9ec5570b2] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(backtrace_get+0x1e) [0x7fa9ec5571ce] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(+0x103e0b) [0x7fa9ec563e0b] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(+0x103ea1) [0x7fa9ec563ea1] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(+0x56400) [0x7fa9ec4b6400] -> /opt/dovecot/lib/dovecot/libdovecot-storage.so.0(+0x403e8) [0x7fa9ec6733e8] -> /opt/dovecot/lib/dovecot/lib20_virtual_plugin.so(virtual_config_read+0x6d) [0x7fa9ec452e2d] -> /opt/dovecot/lib/dovecot/lib20_virtual_plugin.so(+0xb468) [0x7fa9ec455468] -> /opt/dovecot/lib/dovecot/libdovecot-storage.so.0(mailbox_alloc+0xbf) [0x7fa9ec69567f] -> dovecot/imap(client_open_save_dest_box+0x83) [0x557924033b83] -> dovecot/imap(+0x13a66) [0x557924024a66] -> dovecot/imap(command_exec+0xa4) [0x557924033434] -> dovecot/imap(+0x2035f) [0x55792403135f] -> dovecot/imap(+0x2040a) [0x55792403140a] -> dovecot/imap(+0x2071d) [0x55792403171d] -> dovecot/imap(client_handle_input+0x1b5) [0x5579240318e5] -> dovecot/imap(client_input+0x70) [0x557924031e50] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(io_loop_call_io+0x69) [0x7fa9ec57a0f9] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(io_loop_handler_run_internal+0x132) [0x7fa9ec57b7e2] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(io_loop_handler_run+0x50) [0x7fa9ec57a1a0] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(io_loop_run+0x40) [0x7fa9ec57a360] -> /opt/dovecot/lib/dovecot/libdovecot.so.0(master_service_run+0x13) [0x7fa9ec4ee853] -> dovecot/imap(main+0x50c) [0x557924022efc] -> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7fa9ec29bd0a] -> dovecot/imap(_start+0x2a) [0x557924022fca]
Feb 25 12:13:36 locutus dovecot: imap(allgood)<1468376><kJ+PJNnYQpR/AAAB>: Fatal: master: service(imap): child 1468376 killed with signal 6 (core dumps disabled - https://dovecot.org/bugreport.html#coredumps)
```

2022-03-01 11:48 UTC, allgood commented
pinging @sirainen  ... just to check if you saw last message.

2022-03-02 23:16 UTC, sirainen commented
I was testing it now a bit further, and looks like there are some rather major issues with my approach as well. But .. it looks like it just needs a bit of tweaking. mailbox_alloc() calls mailbox_list_get_storage() that allows translating the folder's mailbox_list and mail_storage. So we could:
 * Change mailbox_list_get_storage() & mailbox_list_vfuncs.get_storage_name() so it allows changing also the mailbox vname
 * Also add `enum mailbox_flags flags` parameter to them.
 * Hook virtual plugin into mailbox_list_vfuncs.get_storage_name() where it does similar conversion as what I attempted in my previous patch above.

And .. looks like it worked. Attaching here. See if it works ok? [virtual-save.patch.txt](https://github.com/dovecot/pigeonhole/files/8173562/virtual-save.patch.txt)

2022-03-02 23:56 UTC, sirainen commented
Somehow I'm not able to write a test case which even reproduces the originally reported crash..

2022-03-03 12:34 UTC, allgood commented
Hi @sirainen, thank you!


> And .. looks like it worked. Attaching here. See if it works ok? [virtual-save.patch.txt](https://github.com/dovecot/pigeonhole/files/8173562/virtual-save.patch.txt)

I needed to apply two parts of the patch manually since it failed to apply on main head. After building all three operations worked well on virtual folders:

FLAG message on virtual folder, passing the virtual folder name
APPEND to virtual folder, passing the backend folder name
COPY to virtual folder, passing the backend folder name

> Somehow I'm not able to write a test case which even reproduces the originally reported crash..

I don't know how to do this, and I suppose that testing needs pigeonhole... should the test for this behavior be on pigeonhole project?

Thank you again!

2022-03-03 12:37 UTC, allgood commented
> I needed to apply two parts of the patch manually since it failed to apply on main head.

Just to document, this is the parts that failed to apply on current main head (extracted from .rej files)

```diff
--- src/lib-storage/mailbox-list.c
+++ src/lib-storage/mailbox-list.c
@@ -892,15 +892,13 @@ mailbox_list_get_storage_driver(struct mailbox_list *list, const char *driver,
 	return 0;
 }
 
-int mailbox_list_get_storage(struct mailbox_list **list, const char **vname,
-			     enum mailbox_list_get_storage_flags flags,
-			     struct mail_storage **storage_r)
+int mailbox_list_default_get_storage(struct mailbox_list **list,
+				     const char **vname,
+				     enum mailbox_list_get_storage_flags flags ATTR_UNUSED,
+				     struct mail_storage **storage_r)
 {
 	const struct mailbox_settings *set;
 
-	if ((*list)->v.get_storage != NULL)
-		return (*list)->v.get_storage(list, vname, flags, storage_r);
-
 	set = mailbox_settings_find((*list)->ns, *vname);
 	if (set != NULL && set->driver != NULL && set->driver[0] != '\0') {
 		return mailbox_list_get_storage_driver(*list, set->driver,
--- src/lib-storage/mail-storage.c
+++ src/lib-storage/mail-storage.c
@@ -871,6 +871,7 @@ struct mailbox *mailbox_alloc(struct mailbox_list *list, const char *vname,
 	}
 
 	T_BEGIN {
+		const char *orig_vname = vname;
 		enum mailbox_list_get_storage_flags storage_flags = 0;
 		if ((flags & MAILBOX_FLAG_SAVEONLY) != 0)
 			storage_flags |= MAILBOX_LIST_GET_STORAGE_FLAG_SAVEONLY;
```

2022-03-04 13:10 UTC, sirainen commented
> > Somehow I'm not able to write a test case which even reproduces the originally reported crash..
> 
> I don't know how to do this, and I suppose that testing needs pigeonhole... should the test for this behavior be on pigeonhole project?
> 
> **EDIT:** Pigeonhole is where I'm using this feature, crash doesn't occur if not using it since is it that tries to get the folder path and message contents.

I meant just being able to reproduce it at all. I tried to configure imapsieve-before script like described in the email and then tried COPYing or APPENDing mails to the virtual folder, and the Sieve script was executed fine without crashes. It would help if you can send a way to reproduce, i.e.:
 * full dovecot.conf and sieve script, ideally with e.g. passdb & userdb static so it's not relying on anything external
 * imap commands that cause this with a completely new empty user

2022-03-04 13:28 UTC, allgood commented
@sirainen , will try to pass here all the detais of my testbed:

Configured dovecot using:

```bash
PANDOC=false ./configure --prefix=/opt/dovecot --without-systemd
```

and pigeonhole with:

```bash
./configure --prefix=/opt/dovecot --with-dovecot=${DOVECOT_SOURCE_PATH}
```

Installed bot projects.

I've configured imapsieve to only log that it was working, I'm attaching a tar file with my setup:

* `etc/dovecot` with all configurations of the project (don't remember if I tweaked one of the original project files)
* `wwmail` contains the imapsieve scripts
* `virtual-wwmail` contains the virtual folder configuration

I've tested the imap commands using thunderbird, just moving some messages from local folders to the imap virtual folder to test the APPEND, moving from a real folder to virtual folder to test the COPY/MOVE, and flagging on the virtual folder to test the FLAG.

[dovecot-pigeonhole-imapsieve-config.tar.gz](https://github.com/dovecot/pigeonhole/files/8186189/dovecot-pigeonhole-imapsieve-config.tar.gz)

2022-03-17 13:19 UTC, allgood commented
pinging @sirainen ... do you have any comments on my last message? I am satisfied with the results of the patch you made, hope it gets merged!

2022-05-02 12:59 UTC, allgood commented
sorry pinging you again @sirainen , do you think this development can be merged?

2022-05-02 13:22 UTC, cmouse commented
@allgood please reopen this against main branch.

2022-05-02 13:28 UTC, sirainen commented
@cmouse I have the redesigned patch in DOP-2779, but I got stuck because I couldn't reproduce the problem. And haven't had time to try the latest suggestions..

2022-05-03 18:20 UTC, allgood commented
@sirainen , did you tried the config I posted on March 4?

2022-05-16 18:43 UTC, sirainen commented
I finally tested with your config and using Thunderbird. I copied & moved messages around, from/to virtual.Test & Trash & INBOX & copied from another account. No crashes :(

2022-05-17 14:10 UTC, allgood commented
@sirainen ... the problem isn't crashes... the problem is that the sieve script doesn't run when moving messages to a virtual folder.

2022-05-17 14:12 UTC, allgood commented
Without your patch when moving messages to a virtual folder the associated sieve script does not get activated. After applying your patch from march 2, it worked great!

2022-05-17 14:17 UTC, allgood commented
The crash I reported on Feb, 25 wasn't occurring on HEAD, but only with your previous patch (from Feb, 24) applied, and they occurred only when opening folders on Thunderbird.

2022-05-18 09:42 UTC, sirainen commented
Oh, I thought there was a crash also. Yeah, I can now reproduce the problem and wrote a test. Now it just needs to go through the release process, which might take some time.

2022-05-20 14:03 UTC, allgood commented
Great @sirainen , thank you for your help.

First time I noticed the problem there was a crash, but the crash has been already fixed on HEAD, only the behavior that was wrong!

Thank you again! will wait for the commit!

2022-07-05 12:25 UTC, allgood commented
Hi @sirainen , is there a way to monitor the progress of this patch on the release process?

2022-07-05 13:38 UTC, sirainen commented
It's very close now to being merged to main branch. However, it's only going to the upcoming v2.4 release. Update: actually, there is a comment about it possibly going to v2.3.x after all. Lets see. Anyway, it's not possible for people outside our company to see the release process progress.

2022-07-05 15:37 UTC, sirainen commented
There was actually a bug found in my code, fix:
```
-               *vname = mbox->save_bbox->name;
+               *vname = t_strdup(mbox->save_bbox->name);
```

2022-07-06 18:28 UTC, allgood commented
thank you @sirainen!

2022-07-07 13:47 UTC, sirainen commented
It's now merged to main.

2022-07-07 13:58 UTC, allgood commented
great, suppose is not yet on github but may come soon! thank you again!

2024-01-26 13:19 UTC, allgood commented
Hi @sirainen, 

Looks like this patch isn't on github yet. Can you tell me if it was somehow refused?

2024-01-26 13:26 UTC, cmouse commented
can you please reopen this against main?

2024-01-26 13:38 UTC, allgood commented
hi @cmouse ,

My pull request isn't the ideal changes... @sirainen mentioned on july, 5 2022 that he already made his changes on dovecot-core internally, but looks like it doesn't got to github yet.

2024-01-26 13:41 UTC, cmouse commented
i'll check what's going on.

2024-01-26 14:27 UTC, sirainen commented
The fixes are in:

 * c83c6b656cdc01519d28bc5d99b11222b9fa3fc8
 * d973f4b3ba1b03d2b83d467a660df1fc05a93da8
 * b52e056ca4652812de6fd5255ebd34ec3e565954
 * aeedbb12e74610d83830050297424cf1507fe199
 * 53c4134332ac6c3308dcde8a804f57ce1e665301

2024-01-26 15:05 UTC, allgood commented
great @sirainen ,

I was checking comparing with your first patch as reference! but looks like you changed the way you solved the problem!

Anyway, it is not on any release yet... suspect that this will only get to a release on 2.4.

Thank you.